# UI 生产镜像
FROM --platform=linux/amd64 node:18-alpine AS builder

WORKDIR /app
COPY ui/package*.json ./
RUN npm ci

COPY ui/ .
RUN npm run build

FROM --platform=linux/amd64 nginx:alpine

RUN apk add --no-cache tzdata

COPY --from=builder /app/dist /usr/share/nginx/html

RUN mkdir -p /etc/nginx/ssl

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
