package engine

import (
	"fmt"
	"os"
	"strings"
)

// aideDBDir AIDE 数据库目录
const aideDBDir = "/var/lib/aide"

// Render 将 FIMPolicy 渲染为 aide.conf 格式并写入指定路径
func Render(policy *FIMPolicy, configPath string) error {
	var sb strings.Builder

	// 头部：数据库配置
	sb.WriteString("# Generated by mxsec-platform FIM plugin\n")
	sb.WriteString("# DO NOT EDIT - this file is auto-generated\n\n")

	sb.WriteString(fmt.Sprintf("@@define DBDIR %s\n", aideDBDir))
	sb.WriteString("database_in=file:@@{DBDIR}/aide-mxsec.db.gz\n")
	sb.WriteString("database_out=file:@@{DBDIR}/aide-mxsec.db.new.gz\n")
	sb.WriteString("database_new=file:@@{DBDIR}/aide-mxsec.db.new.gz\n")
	sb.WriteString("gzip_dbout=yes\n\n")

	// 检查级别定义
	sb.WriteString("# Check levels\n")
	sb.WriteString("NORMAL = R+sha512\n")
	sb.WriteString("CONTENT = ftype+sha512\n")
	sb.WriteString("PERMS = ftype+p+u+g+acl+selinux+xattrs\n\n")

	// 监控路径
	if len(policy.WatchPaths) > 0 {
		sb.WriteString("# Watch paths\n")
		for _, wp := range policy.WatchPaths {
			level := wp.Level
			if level == "" {
				level = "NORMAL"
			}
			if wp.Comment != "" {
				sb.WriteString(fmt.Sprintf("# %s\n", wp.Comment))
			}
			sb.WriteString(fmt.Sprintf("%s    %s\n", wp.Path, level))
		}
		sb.WriteString("\n")
	}

	// 排除路径
	if len(policy.ExcludePaths) > 0 {
		sb.WriteString("# Exclude paths\n")
		for _, ep := range policy.ExcludePaths {
			sb.WriteString(fmt.Sprintf("!%s\n", ep))
		}
		sb.WriteString("\n")
	}

	// 写入文件
	if err := os.WriteFile(configPath, []byte(sb.String()), 0600); err != nil {
		return fmt.Errorf("写入 aide 配置文件失败: %w", err)
	}

	return nil
}
